CREATE TABLE USUARIO (IDUSUARIO number(10) NOT NULL, NOMBREUSUARIO varchar2(100), APELLIDOUSUARIO varchar2(100), RUTUSUARIO varchar2(100), GENEROUSUARIO varchar2(100), MAILUSUARIO varchar2(100), DIRECCIONUSUARIO varchar2(100), ESTADOUSUARIO varchar2(100), MOSTRARUSUARIO varchar2(100), PRIMARY KEY (IDUSUARIO));
CREATE TABLE GENERO (IDGENERO number(10) NOT NULL, NOMBREGENERO varchar2(45), PRIMARY KEY (IDGENERO));
CREATE SEQUENCE seq_USUARIO;
CREATE SEQUENCE seq_GENERO;
